In [4]:
import numpy as np
#numpy数组：ndarry
#多维，同质（所有元素类型必须一致），高效

# 一.ndarray

In [5]:
a=[[10,20,30,40],[50,60,70,80]]
a=np.array(a,dtype=int)
#转换为np的数组,dtype定义数据类型：int,float,等
print(a)

[[10 20 30 40]
 [50 60 70 80]]


## 同质

In [14]:
a=np.array([1,'hi'])
#不同类型的会被强制转换（字符串>数字；浮点数>整数）
print(a)

['1' 'hi']


## 属性

### 常见

In [6]:
print('维度：',a.ndim) #numpy of dimensions
print('数组大小：',a.shape)
print('元素个数：',a.size)
print('元素类型：',a.dtype)
#数组名.ndim   返回数组维度
#0维:标量；1维:向量；2维:矩阵；大于3维:张量
#数组名.shape  返回数组行列
#数组名.size   返回数组元素数量
#数组名.dtype  返回数组元素类型

维度： 2
数组大小： (2, 4)
元素个数： 8
元素类型： int64


### 不常见

In [7]:
print('转置',a.T)
print('单个元素占用的内存：',a.itemsize)
print('数组总内存占用：',a.nbytes)
print('内存存储方式',a.flags)

转置 [[10 50]
 [20 60]
 [30 70]
 [40 80]]
单个元素占用的内存： 8
数组总内存占用： 64
内存存储方式   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



## 生成

In [11]:
b=np.copy(a)
#复制数组
#深复制，两者互不影响了
print(b)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [8]:
a=np.zeros((3,4),dtype=int)
#生成一个3行4列全为零的数组(zero全为0，ones全为1，empyt未初始化的)
#一维数组写作(x,)
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [16]:
a=np.full((3,4),5,dtype=float)
#用5来填满一个三行四列的数组
print(a)

[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]


In [17]:
b=np.zeros_like(a,dtype=int)
#形状和a相同，元素全为0
b=np.ones_like(a,dtype=int)
b=np.empty_like(a,dtype=int)
b=np.full_like(a,2,dtype=int)
print(b)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [9]:
a=np.arange(0,10,1).reshape(2,5)
#用法等同于range,reshape规定行列
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [18]:
#等间隔数列
a=np.linspace(0,11,12,dtype=int).reshape(3,4)
#生成一个第一个数为0,最后一个数为11,有12个数的数列,reshape规定行列
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [30]:
#等比数列
a=np.logspace(0,11,12,base=2,dtype=int).reshape(3,4)
#第一个数2的0次方，最后一个数2的4次方，12个数
#不写base默认10
print(a)

[[   1    2    4    8]
 [  16   32   64  128]
 [ 256  512 1024 2048]]


### 特殊矩阵

In [33]:
#单位矩阵
a=np.eye(4,3,dtype=int)
#前两个参数：行，列
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 0]]


In [34]:
#对角矩阵
a=np.diag([4,5,1,2,3,4])
#生成矩阵的大小根据给的元素个数来
print(a)

[[4 0 0 0 0 0]
 [0 5 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 3 0]
 [0 0 0 0 0 4]]


In [46]:
#随机矩阵（均匀分布）
a=np.random.rand(3,4)
#rand:生成0到1之间的随机数，括号中规定行列
print(a)
a=np.random.uniform(1,6,(3,4))
#生成1到6之间的随机浮点数，括号规定行列
print(a)
a=np.random.randint(3,20,(2,3))
#生成3到20之间的随机整数，括号内规定行列
print(a)

[[0.87359474 0.54399809 0.51519485 0.89857096]
 [0.57650494 0.6143858  0.74447842 0.42688548]
 [0.73235049 0.44412857 0.05911131 0.07056699]]
[[1.24732282 5.72423846 5.49900604 3.35553335]
 [5.96629015 5.10643856 3.51360098 5.00525932]
 [2.08322835 1.30813635 4.30930706 2.15923379]]
[[15 10 10]
 [ 3 11 15]]


In [47]:
#随机矩阵（正态分布）
a=np.random.randn(2,3)
#按标准正态分布，括号规定行列
print(a)

[[-0.25060682  0.03906814 -1.52032777]
 [-0.67628558  0.30364909 -0.19497231]]


In [54]:
np.random.seed(20)#设置随机数种子
a=np.random.randint(1,10,(2,3))
#随机数种子相同，则生成的数相同
print(a)

[[4 5 7]
 [8 3 1]]


## 数据类型

In [55]:
#bool  布尔（True/False）
#int  (8,16,32,64)  有符号整形
#uint (8,16,32,64)  无符号整形
#数字表示位数（8位，16位，32位，64位）（1，2，4，8字节）
#float (16,32,64)  浮点数  （半精度，单精度，双精度）
#complex  (64,128) 复数
a=np.array([1,0,1,1,0],dtype=bool)
print(a)

[ True False  True  True False]


## 索引与切片

In [71]:
#基本(一维)
a=np.random.randint(1,10,(10,))
print(a)
#与py的列表类似
print(a[2])
print(a[:])
print(a[2:5])
#过滤
print(a[a>5])
print(a[(a>2)&(a<8)])  #&且   |或
#slice函数
print(a[slice(2,8,2)])  #格式类似range

[4 7 6 5 5 2 9 8 2 3]
6
[4 7 6 5 5 2 9 8 2 3]
[6 5 5]
[7 6 9 8]
[4 7 6 5 5 3]
[6 5 9]


In [ ]:
#二维


## 运算

In [12]:
b=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
c=a-b      #加减：各位依次加减
print(c)

[[-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]]


In [29]:
a=np.sin([1,2,3,4]) #依次计算每个元素的正弦值（弧度
print(a)
a=np.cos(3.1415926535)
print(a)
a=np.tan([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
a=np.pi        #pi值
print(a)
a=np.e
print(a)


[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
-1.0
[[ 1.55740772e+00 -2.18503986e+00 -1.42546543e-01  1.15782128e+00]
 [-3.38051501e+00 -2.91006191e-01  8.71447983e-01 -6.79971146e+00]
 [-4.52315659e-01  6.48360827e-01 -2.25950846e+02 -6.35859929e-01]]
3.141592653589793
2.718281828459045
