In [97]:
import numpy as np
#numpy数组：ndarry
#多维，同质（所有元素类型必须一致），高效

# ndarray

In [98]:
a=[[10,20,30,40],[50,60,70,80]]
a=np.array(a,dtype=int)
#转换为np的数组,dtype定义数据类型：int,float,等
print(a)

[[10 20 30 40]
 [50 60 70 80]]


## 同质

In [99]:
a=np.array([1,'hi'])
#不同类型的会被强制转换（字符串>数字；浮点数>整数）
print(a)

['1' 'hi']


## 属性

### 常见

In [100]:
print('维度：',a.ndim) #numpy of dimensions
print('数组大小：',a.shape)
print('元素个数：',a.size)
print('元素类型：',a.dtype)
#数组名.ndim   返回数组维度
#0维:标量；1维:向量；2维:矩阵；大于3维:张量
#数组名.shape  返回数组行列
#数组名.size   返回数组元素数量
#数组名.dtype  返回数组元素类型

维度： 1
数组大小： (2,)
元素个数： 2
元素类型： <U21


### 不常见

In [101]:
print('转置',a.T)
print('单个元素占用的内存：',a.itemsize)
print('数组总内存占用：',a.nbytes)
print('内存存储方式',a.flags)

转置 ['1' 'hi']
单个元素占用的内存： 84
数组总内存占用： 168
内存存储方式   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



## 生成

In [102]:
b=np.copy(a)
#复制数组
#深复制，两者互不影响了
print(b)

['1' 'hi']


In [103]:
a=np.zeros((3,4),dtype=int)
#生成一个3行4列全为零的数组(zero全为0，ones全为1，empyt未初始化的)
#一维数组写作(x,)
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [104]:
a=np.full((3,4),5,dtype=float)
#用5来填满一个三行四列的数组
print(a)

[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]


In [105]:
b=np.zeros_like(a,dtype=int)
#形状和a相同，元素全为0
b=np.ones_like(a,dtype=int)
b=np.empty_like(a,dtype=int)
b=np.full_like(a,2,dtype=int)
print(b)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [106]:
a=np.arange(0,10,1).reshape(2,5)
#用法等同于range,reshape规定行列
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [107]:
#等间隔数列
a=np.linspace(0,11,12,dtype=int).reshape(3,4)
#生成一个第一个数为0,最后一个数为11,有12个数的数列,reshape规定行列
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [108]:
#等比数列
a=np.logspace(0,11,12,base=2,dtype=int).reshape(3,4)
#第一个数2的0次方，最后一个数2的4次方，12个数
#不写base默认10
print(a)

[[   1    2    4    8]
 [  16   32   64  128]
 [ 256  512 1024 2048]]


### 特殊矩阵

In [109]:
#单位矩阵
a=np.eye(4,3,dtype=int)
#前两个参数：行，列
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 0]]


In [110]:
#对角矩阵
a=np.diag([4,5,1,2,3,4])
#生成矩阵的大小根据给的元素个数来
print(a)

[[4 0 0 0 0 0]
 [0 5 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 3 0]
 [0 0 0 0 0 4]]


In [111]:
#随机矩阵（均匀分布）
a=np.random.rand(3,4)
#rand:生成0到1之间的随机数，括号中规定行列
print(a)
a=np.random.uniform(1,6,(3,4))
#生成1到6之间的随机浮点数，括号规定行列
print(a)
a=np.random.randint(3,20,(2,3))
#生成3到20之间的随机整数，括号内规定行列
print(a)

[[0.15398343 0.0373574  0.97943887 0.36672281]
 [0.81242047 0.67803293 0.39862547 0.55632886]
 [0.24929158 0.3168374  0.85260133 0.56196784]]
[[3.26549529 3.43944636 4.42159382 4.77849342]
 [5.05723713 5.45820496 5.42809482 5.98799668]
 [1.9614806  5.6383335  4.02776073 2.94269172]]
[[18 15  4]
 [ 8 10  5]]


In [112]:
#随机矩阵（正态分布）
a=np.random.randn(2,3)
#按标准正态分布，括号规定行列
print(a)

[[ 1.18940658  0.77504412  0.65636109]
 [-1.4545849   0.88243928 -0.03284662]]


In [113]:
np.random.seed(20)#设置随机数种子
a=np.random.randint(1,10,(2,3))
#随机数种子相同，则生成的数相同
print(a)

[[4 5 7]
 [8 3 1]]


## 数据类型

In [114]:
#bool  布尔（True/False）
#int  (8,16,32,64)  有符号整形
#uint (8,16,32,64)  无符号整形
#数字表示位数（8位，16位，32位，64位）（1，2，4，8字节）
#float (16,32,64)  浮点数  （半精度，单精度，双精度）
#complex  (64,128) 复数
a=np.array([1,0,1,1,0],dtype=bool)
print(a)

[ True False  True  True False]


## 索引与切片

In [115]:
#基本(一维)
a=np.random.randint(1,10,(10,))
print(a)
#与py的列表类似
print(a[2])
print(a[:])
print(a[2:5])
#过滤
print(a[a>5])
print(a[(a>2)&(a<8)])  #&且   |或
#slice函数
print(a[slice(2,8,2)])  #格式类似range

[7 9 6 4 1 7 7 1 6 8]
6
[7 9 6 4 1 7 7 1 6 8]
[6 4 1]
[7 9 6 7 7 6 8]
[7 6 4 7 7 6]
[6 1 7]


In [116]:
#多维
a=np.random.randint(1,10,(2,3,3))
print(a)
print(a[1,0,2])  #索引：逗号分隔
print(a[1][0][2]) #也可以
print(a[:,:,:])  #几维几个冒号
print(a[0,0:2,0:2])  #每维单独控制
print(a[a>4])   #筛选出来，放在一个一维数组中
print(a[0][a[0]>4])    #可以这样先切片再筛选

[[[6 3 7]
  [4 4 1]
  [7 3 4]]

 [[2 9 1]
  [3 8 7]
  [7 9 3]]]
1
1
[[[6 3 7]
  [4 4 1]
  [7 3 4]]

 [[2 9 1]
  [3 8 7]
  [7 9 3]]]
[[6 3]
 [4 4]]
[6 7 7 9 8 7 7 9]
[6 7 7]


## 运算

In [117]:
#加减乘除，各位上对应的元素依次运算
a=np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])
b=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a-b)
print(a+b)
print(a*b)
print(a/b)

[[  9  18  27  36]
 [ 45  54  63  72]
 [ 81  90  99 108]]
[[ 11  22  33  44]
 [ 55  66  77  88]
 [ 99 110 121 132]]
[[  10   40   90  160]
 [ 250  360  490  640]
 [ 810 1000 1210 1440]]
[[10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]]


In [118]:
#和数运算：与每一个元素进行运算
a=np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])
b=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a-1)
print(a+2)
print(a*2)
print(a/10)

[[  9  19  29  39]
 [ 49  59  69  79]
 [ 89  99 109 119]]
[[ 12  22  32  42]
 [ 52  62  72  82]
 [ 92 102 112 122]]
[[ 20  40  60  80]
 [100 120 140 160]
 [180 200 220 240]]
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


In [119]:
#广播机制
#少的向多的填充，再运算
a=np.array([1,2,3])   #1*3
b=np.array([[4],[5],[6]])  #3*1
print(a+b)
#少用，易错，确保运算前合法

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [120]:
#矩阵乘法
a=np.array([[1,2,3,10],[4,5,6,11],[7,8,9,12]])
b=np.array([[10,20,30],[40,50,60]])
print(b@a)     #  @表示矩阵乘法（线代）
#前m*n  后n*t  结果m*t

[[ 300  360  420  680]
 [ 660  810  960 1670]]


# numpy常用函数

## 基本数学

In [121]:
#常量
a=np.pi
print(a)
a=np.e
print(a)

3.141592653589793
2.718281828459045


In [122]:
a=np.sin([1,2,3,4]) #依次计算每个元素的正弦值（弧度
print(a)
a=np.cos(3.1415926535)
print(a)
a=np.tan([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
-1.0
[[ 1.55740772e+00 -2.18503986e+00 -1.42546543e-01  1.15782128e+00]
 [-3.38051501e+00 -2.91006191e-01  8.71447983e-01 -6.79971146e+00]
 [-4.52315659e-01  6.48360827e-01 -2.25950846e+02 -6.35859929e-01]]


In [123]:
a=np.array([1,2,3,4])
print(np.sqrt(a))  #计算平方根
print(np.exp(a))  #计算指数（e为底）
print(np.log(a))  #计算对数（e为底）

[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]


In [124]:
print(np.abs(a)) #计算绝对值
print(np.power(a,3)) #计算a的3次幂

[1 2 3 4]
[ 1  8 27 64]


In [125]:
a=np.array([1.1,3.7,4.2,4.5,4.55,4.51,5.6])
print(np.round(a))  #四舍五入
#<=.5舍，>.5入
print(np.ceil(a)) #向上取整
print(np.floor(a)) #向下取整

[1. 4. 4. 4. 5. 5. 6.]
[2. 4. 5. 5. 5. 5. 6.]
[1. 3. 4. 4. 4. 4. 5.]


In [126]:
a=np.full((3,4),np.nan,dtype=float)  #NaN:表示空缺值
a[0][0]=1
print(a)
print(np.isnan(a))  #检查元素是不是空缺值（是则True，不是则False

[[ 1. nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
[[False  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


## 统计函数

In [127]:
a=np.random.randint(1,10,(3,4))
print(a)
print(np.sum(a))  #求和
print(np.mean(a)) #平均值
print(np.median(a)) #中位数
print(np.var(a))  #方差
print(np.std(a))  #标准差（方差开方）

[[2 4 3 7]
 [5 7 5 9]
 [7 3 4 2]]
58
4.833333333333333
4.5
4.638888888888888
2.153807997220014


In [128]:
a=np.random.randint(1,10,(3,4))
print(a)
print(np.max(a),np.argmax(a)) #最大值，第几个
print(np.min(a),np.argmin(a)) #最小值，第几个

[[6 3 2 9]
 [3 5 5 9]
 [7 1 4 5]]
9 3
1 9


In [129]:
a=np.random.randint(1,10,(3,4))
print(a)
print(np.percentile(a,95)) #百分位数

[[1 6 7 8]
 [5 1 7 2]
 [7 8 8 7]]
8.0


In [130]:
a=np.random.randint(1,10,(3,4))
print(a)
print(np.cumsum(a)) #累计和
#生成一个一维数组，依次表示前一个，前两个，前三个……的和
print(np.cumprod(a)) #累计积 （和累计和类似

[[9 9 3 3]
 [2 6 3 8]
 [6 6 7 6]]
[ 9 18 21 24 26 32 35 43 49 55 62 68]
[        9        81       243       729      1458      8748     26244
    209952   1259712   7558272  52907904 317447424]


## 比较函数

In [131]:
a=np.random.randint(1,10,(3,4))
b=np.random.randint(1,10,(3,4))
print(a)
print(b)
print(np.greater(a,5))  #a是否大于5
print(np.less(a,5)) #a是否小于5
print(np.greater(a,b)) #a是否大于b（逐个元素比较）
print(np.equal(a,5))  #a是否等于5

[[3 7 2 9]
 [2 1 9 6]
 [1 7 6 5]]
[[3 5 6 4]
 [8 2 3 4]
 [7 6 5 5]]
[[False  True False  True]
 [False False  True  True]
 [False  True  True False]]
[[ True False  True False]
 [ True  True False False]
 [ True False False False]]
[[False  True False  True]
 [False False  True  True]
 [False  True  True False]]
[[False False False False]
 [False False False False]
 [False False False  True]]


In [132]:
a=np.random.randint(1,10,(3,4))
b=np.random.randint(1,10,(3,4))
print(a)
print(b)
print(np.logical_and(a,b)) #逻辑与
print(np.logical_or(a,b)) #逻辑或
print(np.logical_not(a)) #逻辑非

[[2 9 8 2]
 [3 4 5 5]
 [5 1 6 5]]
[[4 3 8 1]
 [7 3 8 6]
 [8 8 6 7]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[False False False False]
 [False False False False]
 [False False False False]]


In [133]:
a=np.random.randint(-10,10,(3,4))
print(a)
print(np.any(a)) #检查元素是否至少有一个为True
print(np.all(a)) #检查元素是否全为True

[[ -9  -4   2  -6]
 [ -4 -10  -3   4]
 [ -8  -4   8   1]]
True
True


In [134]:
a=np.random.randint(-10,10,(3,4))
print(a)
#np.where(条件,符合条件,不符合条件)
print(np.where(a>0,a,0))
#自定义条件，符合条件从2取，不符合从3取
#可进行嵌套来分类筛选
print(np.where(a<-3,a,np.where(a>3,a,0)))
print(np.select([a<-3,(a>=-3)&(a<=3),a>3],[a,0,a]))
#select:两个列表依次写条件和结果，一一对应

[[ 9  5 -2  1]
 [-4 -9 -1  6]
 [ 6 -3  2 -1]]
[[9 5 0 1]
 [0 0 0 6]
 [6 0 2 0]]
[[ 9  5  0  0]
 [-4 -9  0  6]
 [ 6  0  0  0]]
[[ 9  5  0  0]
 [-4 -9  0  6]
 [ 6  0  0  0]]


## 排序函数

In [135]:
a=np.random.randint(1,10,(9,))
print(a)
a.sort()  #按升序进行每行排序，修改原数组，无返回值
print(a)
print(np.sort(a)) #按升序进行每行排序，不修改原数组，返回新数组
print(np.unique(a)) #去重，排序
print(np.argsort(a))  #大小不变，元素重填

[3 4 8 5 2 4 3 2 7]
[2 2 3 3 4 4 5 7 8]
[2 2 3 3 4 4 5 7 8]
[2 3 4 5 7 8]
[0 1 2 3 4 5 6 7 8]


## 其他

In [136]:
print(np.concatenate([[1,2,3],[4,5,6]])) #拼接
print(np.split([1,2,3,4,5,6],[2,5]))#以第二个中的元素为分界线切割第一个

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4, 5]), array([6])]


In [137]:
a=np.random.randint(1,10,(8,))
print(a)
print(np.reshape(a,(2,4))) #调整数组形状

[6 6 7 5 3 1 5 9]
[[6 6 7 5]
 [3 1 5 9]]
